ALTER TABLE site_hero_images
  MODIFY COLUMN viewport_target ENUM('DESKTOP_TABLET','TABLET_LAPTOP','MOBILE') NOT NULL DEFAULT 'DESKTOP_TABLET';

SELECT COLUMN_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'site_hero_images'
  AND COLUMN_NAME = 'viewport_target';
